include_guard(GLOBAL)

function(cpr_report_dependency name found required)
    if(${found})
        message(STATUS "${name}: FOUND")
    elseif(required)
        if(CPR_REQUIRE_ALL_DEPENDENCIES)
            message(FATAL_ERROR "${name}: NOT FOUND and CPR_REQUIRE_ALL_DEPENDENCIES=ON")
        else()
            message(WARNING "${name}: NOT FOUND (continuing because CPR_REQUIRE_ALL_DEPENDENCIES=OFF)")
        endif()
    else()
        message(STATUS "${name}: NOT FOUND (optional)")
    endif()
endfunction()

function(cpr_detect_dependencies target)
    find_package(Protobuf CONFIG QUIET)
    if(NOT Protobuf_FOUND)
        find_package(Protobuf QUIET)
    endif()
    cpr_report_dependency("Protobuf" Protobuf_FOUND TRUE)
    if(Protobuf_FOUND AND TARGET protobuf::libprotobuf)
        target_link_libraries(${target} INTERFACE protobuf::libprotobuf)
    endif()

    find_package(gRPC CONFIG QUIET)
    cpr_report_dependency("gRPC" gRPC_FOUND TRUE)
    if(gRPC_FOUND AND TARGET gRPC::grpc++)
        target_link_libraries(${target} INTERFACE gRPC::grpc++)
    endif()

    find_package(GTest CONFIG QUIET)
    if(NOT GTest_FOUND)
        find_package(GTest QUIET)
    endif()
    cpr_report_dependency("GoogleTest" GTest_FOUND TRUE)
    if(GTest_FOUND AND TARGET GTest::gtest)
        target_link_libraries(${target} INTERFACE GTest::gtest)
    endif()

    find_package(nlohmann_json CONFIG QUIET)
    cpr_report_dependency("nlohmann_json" nlohmann_json_FOUND TRUE)
    if(nlohmann_json_FOUND AND TARGET nlohmann_json::nlohmann_json)
        target_link_libraries(${target} INTERFACE nlohmann_json::nlohmann_json)
    endif()

    find_package(spdlog CONFIG QUIET)
    cpr_report_dependency("spdlog" spdlog_FOUND FALSE)
    if(spdlog_FOUND AND TARGET spdlog::spdlog)
        target_link_libraries(${target} INTERFACE spdlog::spdlog)
    endif()
endfunction()
